version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0
    steps:
      - checkout
      - run:
          name: Setup Maven
          command: mvn -version
      - run:
          name: Build with Maven
          command: mvn clean package -DskipTests
  test:
    docker:
      - image: cimg/openjdk:23.0
    steps:
      - checkout
      - run:
          name: Test with Maven
          command: mvn test

workflows:
  build_and_test:
    jobs:
      - build:
        filters:
            branches:
              only: master
      - test:
          requires:
            - build
