version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package
  
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Test with Maven
          command: mvn test

workflows:
  build_and_test:
    jobs:
      - build:
        filters:
            branches:
              only: master

      - test:
          requires:
            - build
