version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Setup Maven
          command: mvn -version
      - run:
          name: Build and Test with Maven
          command: mvn clean test

workflows:
  build_and_test:
    jobs:
      - build:
        filters:
            branches:
              only: master
      - test:
          requires:
            - build
