version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0
    steps:
      - checkout
      - run:
          name: Setup Maven
          command: mvn -version
      - run:
          name: Build With Maven
          command: mvn clean package -DskipTests
      - run:
          name: Generate Javadoc
          command: mvn -B javadoc:javadoc

  test:
    docker:
      - image: cimg/openjdk:23.0
    steps:
      - checkout
      - run:
          name: Test With Maven
          command: mvn test jacoco:report
      - run:
          name: Generate JaCoCo Coverage Report
          command: mvn jacoco:report
      - run:
          name: Generate and copy Checkstyle report with badge
          command: |
            mvn checkstyle:checkstyle
            python scripts/checkstyle_to_json.py
      - run:
          name: Publish checkstyle badge to GitHub
          command: |
            git config --global user.email "kissouna.b@gmail.com"
            git config --global user.name "BradleyKissouna"
            git config --global push.autoSetupRemote always
            git add docs/
            git commit -m "Update Checkstyle badge"
            git push
      - codecov/upload

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
